# ===============================================================
#  gmail_plugin.py  —  FRIDAY Gmail Integration
#  • Send emails via Gmail API (content generated by Ollama)
#  • Monitor inbox in background, toast notification on new mail
#  • AI-generated reply shown in notification → Yes / No buttons
# ===============================================================

import os
import base64
import threading
import time
import json
import requests
import subprocess
import re
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

from voice import speak

# ── Scopes: read + send ──────────────────────────────────────────
SCOPES = [
    "https://www.googleapis.com/auth/gmail.readonly",
    "https://www.googleapis.com/auth/gmail.send",
    "https://www.googleapis.com/auth/gmail.modify",   # needed to mark as read
]

# ── Credentials paths (relative to this file) ────────────────────
BASE_DIR        = os.path.dirname(os.path.abspath(__file__))
CREDENTIALS_FILE = os.path.join(BASE_DIR, "credentials.json")
TOKEN_FILE       = os.path.join(BASE_DIR, "gmail_token.json")

# ── Email contacts (name → gmail address) ────────────────────────
EMAIL_CONTACTS = {
    "dad":  os.getenv("EMAIL_DAD",  ""),     # set in .env  e.g. EMAIL_DAD=dad@gmail.com
    "mom":  os.getenv("EMAIL_MOM",  ""),
    "me":   os.getenv("EMAIL_ME",   ""),     # your own address, used as fallback sender label
}

# ── Ollama config (reuse config.py values) ────────────────────────
OLLAMA_URL   = os.getenv("OLLAMA_URL",   "http://localhost:11434/api/generate")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "phi3")

# ── Monitoring interval (seconds between inbox checks) ───────────
POLL_INTERVAL = 60   # check every 60 seconds
_seen_ids: set = set()
_monitor_running = False


# ================================================================
#  AUTH
# ================================================================

def get_gmail_service():
    """Return an authenticated Gmail API service object."""
    creds = None

    if os.path.exists(TOKEN_FILE):
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(CREDENTIALS_FILE, SCOPES)
            creds = flow.run_local_server(port=0)

        with open(TOKEN_FILE, "w") as f:
            f.write(creds.to_json())

    return build("gmail", "v1", credentials=creds)


# ================================================================
#  UNREAD COUNT (used by task_queue.start_proactive_loop)
# ================================================================

def get_unread_count() -> int:
    """Return the number of unread messages in the inbox, or 0 on error."""
    try:
        service = get_gmail_service()
        result = service.users().messages().list(
            userId="me", labelIds=["INBOX", "UNREAD"], maxResults=50
        ).execute()
        return len(result.get("messages", []))
    except Exception as e:
        print(f"[GMAIL] get_unread_count error: {e}")
        return 0


# ================================================================
#  OLLAMA HELPER
# ================================================================

def _ask_ollama(prompt: str) -> str:
    """Ask local Ollama model and return the response text."""
    try:
        resp = requests.post(
            OLLAMA_URL,
            json={"model": OLLAMA_MODEL, "prompt": prompt, "stream": False},
            timeout=60,
        )
        resp.raise_for_status()
        return resp.json().get("response", "").strip()
    except Exception as e:
        print(f"[GMAIL] Ollama error: {e}")
        return ""


# ================================================================
#  SEND EMAIL
# ================================================================

def compose_and_send(recipient_name: str, subject_hint: str = "", body_hint: str = "") -> bool:
    """
    Generate an email with Ollama and send it via Gmail API.
    recipient_name — key in EMAIL_CONTACTS  (e.g. "dad")
    subject_hint   — what the email is about (optional, from voice command)
    body_hint      — extra context (optional)
    """
    recipient_name = recipient_name.lower().strip()

    # ── Resolve address ──
    to_address = EMAIL_CONTACTS.get(recipient_name)
    if not to_address:
        speak(f"I don't have an email address for {recipient_name}. Please add it to EMAIL_CONTACTS in gmail_plugin.py or your .env file.")
        return False

    # ── Ask Ollama to draft the email ──
    prompt = (
        f"Write a short, friendly email"
        f"{' about: ' + subject_hint if subject_hint else ''}."
        f"{' Additional context: ' + body_hint if body_hint else ''}"
        f"\n\nReturn ONLY valid JSON with exactly two keys: \"subject\" and \"body\"."
        f" No markdown, no backticks, no preamble."
    )

    speak(f"Drafting email to {recipient_name}…")
    raw = _ask_ollama(prompt)

    # ── Parse JSON from Ollama ──
    subject = "Hi from FRIDAY"
    body    = raw   # fallback: treat entire response as body

    try:
        # Strip any accidental markdown fences
        clean = re.sub(r"```[a-z]*", "", raw).strip().strip("`").strip()
        data   = json.loads(clean)
        subject = data.get("subject", subject)
        body    = data.get("body",    raw)
    except Exception:
        print("[GMAIL] Could not parse JSON from Ollama — using raw text as body.")

    print(f"[GMAIL] Subject : {subject}")
    print(f"[GMAIL] Body    :\n{body}")

    # ── Build MIME message ──
    message = MIMEMultipart()
    message["to"]      = to_address
    message["subject"] = subject
    message.attach(MIMEText(body, "plain"))

    raw_bytes = base64.urlsafe_b64encode(message.as_bytes()).decode()

    # ── Send via API ──
    try:
        service = get_gmail_service()
        service.users().messages().send(
            userId="me",
            body={"raw": raw_bytes}
        ).execute()
        speak(f"Email sent to {recipient_name}.")
        print(f"[GMAIL] Email sent to {to_address}")
        return True
    except HttpError as e:
        print(f"[GMAIL] Send error: {e}")
        speak("Sorry, I couldn't send the email. Check the console for details.")
        return False


# ================================================================
#  INBOX MONITOR
# ================================================================

def _get_new_messages(service) -> list[dict]:
    """Return list of unread messages not seen before."""
    try:
        result = service.users().messages().list(
            userId="me",
            labelIds=["INBOX", "UNREAD"],
            maxResults=10,
        ).execute()
        messages = result.get("messages", [])
        new = [m for m in messages if m["id"] not in _seen_ids]
        return new
    except HttpError as e:
        print(f"[GMAIL MONITOR] List error: {e}")
        return []


def _fetch_message_details(service, msg_id: str) -> dict:
    """Fetch sender, subject, snippet for a message."""
    try:
        msg = service.users().messages().get(
            userId="me", id=msg_id, format="metadata",
            metadataHeaders=["From", "Subject"]
        ).execute()

        headers = {h["name"]: h["value"] for h in msg["payload"]["headers"]}
        snippet = msg.get("snippet", "")
        return {
            "id":      msg_id,
            "from":    headers.get("From", "Unknown"),
            "subject": headers.get("Subject", "(no subject)"),
            "snippet": snippet,
        }
    except Exception as e:
        print(f"[GMAIL MONITOR] Fetch error: {e}")
        return {}


def _generate_reply(details: dict) -> str:
    """Ask Ollama to draft a brief reply to an incoming email."""
    prompt = (
        f"Someone sent me an email.\n"
        f"From: {details['from']}\n"
        f"Subject: {details['subject']}\n"
        f"Preview: {details['snippet']}\n\n"
        f"Write a short, polite reply. "
        f"Return ONLY JSON with keys \"subject\" and \"body\". No markdown."
    )
    return _ask_ollama(prompt)


def _send_reply(service, original_id: str, to_address: str, reply_subject: str, reply_body: str):
    """Send a reply to the given message."""
    message = MIMEMultipart()
    message["to"]      = to_address
    message["subject"] = reply_subject if reply_subject.startswith("Re:") else f"Re: {reply_subject}"
    message.attach(MIMEText(reply_body, "plain"))

    raw_bytes = base64.urlsafe_b64encode(message.as_bytes()).decode()

    try:
        service.users().messages().send(
            userId="me",
            body={"raw": raw_bytes, "threadId": original_id}
        ).execute()
        print(f"[GMAIL MONITOR] Reply sent to {to_address}")
        speak("Reply sent.")
    except HttpError as e:
        print(f"[GMAIL MONITOR] Reply error: {e}")
        speak("Reply failed. Check the console.")


def _mark_as_read(service, msg_id: str):
    try:
        service.users().messages().modify(
            userId="me", id=msg_id,
            body={"removeLabelIds": ["UNREAD"]}
        ).execute()
    except Exception:
        pass


def _show_toast_with_reply(details: dict, reply_subject: str, reply_body: str):
    """
    Show a Windows toast notification using PowerShell.
    Buttons: Yes (send reply) | No (ignore)
    Stores reply payload so the monitor loop can pick it up after user choice.
    """
    sender   = details["from"]
    subject  = details["subject"]
    snippet  = details["snippet"][:120].replace('"', "'")

    # ── Persist reply payload for the callback ──
    payload = {
        "msg_id":        details["id"],
        "to":            sender,
        "reply_subject": reply_subject,
        "reply_body":    reply_body,
    }
    payload_path = os.path.join(BASE_DIR, "_pending_reply.json")
    with open(payload_path, "w") as f:
        json.dump(payload, f)

    # ── Build PowerShell toast (Windows Toast Notification via BurntToast or fallback msg) ──
    ps_script = f"""
Add-Type -AssemblyName System.Windows.Forms
$result = [System.Windows.Forms.MessageBox]::Show(
    "From: {sender}`nSubject: {subject}`n`n{snippet}`n`n--- AI Reply Preview ---`n{reply_body[:200].replace(chr(34), chr(39))}",
    "New Email — FRIDAY",
    [System.Windows.Forms.MessageBoxButtons]::YesNo,
    [System.Windows.Forms.MessageBoxIcon]::Information
)
$result | Out-File -FilePath "{payload_path}.choice" -Encoding UTF8
"""

    def _show():
        try:
            result = subprocess.run(
                ["powershell", "-NonInteractive", "-Command", ps_script],
                capture_output=True, text=True, timeout=120
            )
            choice_file = payload_path + ".choice"
            if os.path.exists(choice_file):
                with open(choice_file) as f:
                    choice = f.read().strip()
                os.remove(choice_file)

                if choice == "Yes":
                    print("[GMAIL] User approved reply — sending…")
                    speak("Sending reply…")
                    try:
                        with open(payload_path) as pf:
                            p = json.load(pf)
                        svc = get_gmail_service()
                        _send_reply(svc, p["msg_id"], p["to"], p["reply_subject"], p["reply_body"])
                    except Exception as e:
                        print(f"[GMAIL] Reply dispatch error: {e}")
                else:
                    print("[GMAIL] User declined reply.")
                    speak("Okay, reply discarded.")

                if os.path.exists(payload_path):
                    os.remove(payload_path)
        except Exception as e:
            print(f"[GMAIL TOAST] Error: {e}")

    threading.Thread(target=_show, daemon=True).start()


def _monitor_loop():
    """Background thread: poll Gmail every POLL_INTERVAL seconds."""
    global _seen_ids
    print("[GMAIL MONITOR] Started.")

    try:
        service = get_gmail_service()
    except Exception as e:
        print(f"[GMAIL MONITOR] Auth failed: {e}")
        return

    # ── Seed seen_ids with messages already in inbox (don't notify on startup) ──
    try:
        result = service.users().messages().list(
            userId="me", labelIds=["INBOX", "UNREAD"], maxResults=50
        ).execute()
        _seen_ids = {m["id"] for m in result.get("messages", [])}
        print(f"[GMAIL MONITOR] Seeded with {len(_seen_ids)} existing unread messages.")
    except Exception as e:
        print(f"[GMAIL MONITOR] Seed error: {e}")

    while _monitor_running:
        time.sleep(POLL_INTERVAL)

        try:
            new_messages = _get_new_messages(service)
            for msg in new_messages:
                _seen_ids.add(msg["id"])
                details = _fetch_message_details(service, msg["id"])
                if not details:
                    continue

                print(f"[GMAIL MONITOR] New email: {details['subject']} from {details['from']}")
                speak(f"New email from {details['from'].split('<')[0].strip()}. Subject: {details['subject']}")

                # Generate AI reply
                raw_reply = _generate_reply(details)
                reply_subject = details["subject"]
                reply_body    = raw_reply

                try:
                    clean = re.sub(r"```[a-z]*", "", raw_reply).strip().strip("`")
                    data  = json.loads(clean)
                    reply_subject = data.get("subject", reply_subject)
                    reply_body    = data.get("body",    raw_reply)
                except Exception:
                    pass

                # Show toast with Yes/No
                _show_toast_with_reply(details, reply_subject, reply_body)

                # Mark as read so we don't re-process
                _mark_as_read(service, msg["id"])

        except Exception as e:
            print(f"[GMAIL MONITOR] Poll error: {e}")


# ================================================================
#  PUBLIC API
# ================================================================

def start_monitor():
    """Start background Gmail inbox monitor. Safe to call once at startup."""
    global _monitor_running
    if _monitor_running:
        return
    _monitor_running = True
    t = threading.Thread(target=_monitor_loop, daemon=True)
    t.start()


def stop_monitor():
    global _monitor_running
    _monitor_running = False


# ================================================================
#  BRAIN.PY HANDLER
# ================================================================

# Prefixes that trigger the email intent
EMAIL_SEND_PREFIXES = [
    "send email to",
    "email to",
    "send an email to",
    "write an email to",
    "compose email to",
    "compose an email to",
    "draft email to",
    "draft an email to",
    "send mail to",
]

def is_email_command(command: str) -> bool:
    cmd = command.lower().strip()
    return any(cmd.startswith(p) for p in EMAIL_SEND_PREFIXES) or "send email" in cmd

def handle(command: str) -> bool:
    """Entry point called by brain.py PLUGIN_MAP for 'email' intent."""
    cmd = command.lower().strip()

    matched_prefix = None
    for p in EMAIL_SEND_PREFIXES:
        if cmd.startswith(p):
            matched_prefix = p
            break

    if not matched_prefix:
        # fallback: try to find recipient after "email"
        m = re.search(r"email\s+(?:to\s+)?(\w+)\s*(.*)", cmd)
        if m:
            recipient = m.group(1)
            hint      = m.group(2).strip()
            return compose_and_send(recipient, body_hint=hint)
        speak("I didn't catch who to send the email to.")
        return False

    rest = cmd[len(matched_prefix):].strip()

    # Split on "about" or "saying" or "regarding"
    for sep in ["about", "saying", "regarding", "that says"]:
        if sep in rest:
            parts = rest.split(sep, 1)
            recipient = parts[0].strip()
            hint      = parts[1].strip()
            return compose_and_send(recipient, subject_hint=hint, body_hint=hint)

    # No content hint — just recipient name
    return compose_and_send(rest)